name: Testes

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar pytest
        run: pip install pytest

      - name: Executar testes
        run: python -m pytest