name: Testes

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Security Scan
        uses: gitleaks/gitleaks-action@v2

      - name: Instalar pytest
        run: pip install pytest

      - name: Instalar flake8
        run: pip install flake8
      - name: Executar Linter
        run: python -m flake8 ./calculadora.py
         
      - name: Executar teste unitário
        run: python -m pytest