name: Testes

on:
  push:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Security Scan
        uses: gitleaks/gitleaks-action@v2

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar testes
        run: python -m flake8 seu_arquivo.py
        run: python -m pytest